### ISSUE TITLE
Update release of GHA action

### ISSUE THREAD

**Issue by JakubSzuber** [kubescape/github-action#48]
Workflow fails because of the bugs in the latest version of kubescape/github-action. The bugs are already fixed for the basic Kubescape repo in issues https://github.com/kubescape/kubescape/issues/1271 and https://github.com/kubescape/kubescape/issues/1255 but for now the fixes are not yet implemented in Kubescape action. 

```yaml
name: Suggest autofixes with Kubescape for PR by reviews
on:
  pull_request_target:

jobs:
  kubescape-fix-pr-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - uses: kubescape/github-action@main
      with:
        account: ${{secrets.KUBESCAPE_ACCOUNT}}
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        fixFiles: true
        format: "sarif"
    - name: PR Suggester according to SARIF file
      if: github.event_name == 'pull_request_target'
      uses: HollowMan6/sarif4reviewdog@v1.0.0
      with:
        file: 'results.sarif'
        level: warning
```
